//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FToCClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FahrenheitToCelsius", ReplyAction="http://tempuri.org/IService/FahrenheitToCelsiusResponse")]
        double FahrenheitToCelsius(double fahrenheitDegree);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FahrenheitToCelsius", ReplyAction="http://tempuri.org/IService/FahrenheitToCelsiusResponse")]
        System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double fahrenheitDegree);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CelsiusToFahrenheit", ReplyAction="http://tempuri.org/IService/CelsiusToFahrenheitResponse")]
        double CelsiusToFahrenheit(double celsiusDegree);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CelsiusToFahrenheit", ReplyAction="http://tempuri.org/IService/CelsiusToFahrenheitResponse")]
        System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double celsiusDegree);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : FToCClient.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<FToCClient.ServiceReference1.IService>, FToCClient.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double FahrenheitToCelsius(double fahrenheitDegree) {
            return base.Channel.FahrenheitToCelsius(fahrenheitDegree);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double fahrenheitDegree) {
            return base.Channel.FahrenheitToCelsiusAsync(fahrenheitDegree);
        }
        
        public double CelsiusToFahrenheit(double celsiusDegree) {
            return base.Channel.CelsiusToFahrenheit(celsiusDegree);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double celsiusDegree) {
            return base.Channel.CelsiusToFahrenheitAsync(celsiusDegree);
        }
    }
}
